version: "3.8"
services:
  scrapyd:
    image: zwilson/scrapyd
    build: .
    ports:
      - 6800:6800
    volumes:
      - ./data:/home/scrapyd/data
      - ./scrapyd.conf:/home/scrapyd/scrapyd.conf
    entrypoint: scrapyd
